import { drizzle } from 'drizzle-orm/node-postgres';
import { feelings as feelingsTable } from '../drizzle/schema.js';

const db = drizzle(process.env.DATABASE_URL!);

const feelings = [
	{ nameDE: 'erschrocken', nameEN: 'startled', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'bestürzt', nameEN: 'dismayed', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'betroffen', nameEN: 'affected', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'perplex', nameEN: 'perplexed', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'schockiert', nameEN: 'shocked', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'verschreckt', nameEN: 'scared', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'verunsichert', nameEN: 'unsettled', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'erschüttert', nameEN: 'shaken', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'fassungslos', nameEN: 'speechless', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'sprachlos', nameEN: 'speechless', category: 'startled', positive: false, sort: 1 },
	{ nameDE: 'hilflos', nameEN: 'helpless', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'ratlos', nameEN: 'clueless', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'entmutigt', nameEN: 'discouraged', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'ernüchtert', nameEN: 'disillusioned', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'frustriert', nameEN: 'frustrated', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'gehemmt', nameEN: 'inhibited', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'verloren', nameEN: 'lost', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'machtlos', nameEN: 'powerless', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'ohnmächtig', nameEN: 'powerless', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'überfordert', nameEN: 'overwhelmed', category: 'helpless', positive: false, sort: 1 },
	{ nameDE: 'ängstlich', nameEN: 'anxious', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'furchtsam', nameEN: 'fearful', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'misstrauisch', nameEN: 'distrustful', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'argwöhnisch', nameEN: 'suspicious', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'skeptisch', nameEN: 'skeptical', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'unsicher', nameEN: 'uncertain', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'zögerlich', nameEN: 'hesitant', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'beunruhigt', nameEN: 'worried', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'alarmiert', nameEN: 'alarmed', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'panisch', nameEN: 'panicked', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'verängstigt', nameEN: 'frightened', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'besorgt', nameEN: 'concerned', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'nervös', nameEN: 'nervous', category: 'anxious', positive: false, sort: 1 },
	{ nameDE: 'aufgewühlt', nameEN: 'agitated', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'distressed', nameEN: 'distressed', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'verstört', nameEN: 'disturbed', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'bekümmert', nameEN: 'troubled', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'unruhig', nameEN: 'restless', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'unausgeglichen', nameEN: 'unbalanced', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'aufgebracht', nameEN: 'upset', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'angespannt', nameEN: 'tense', category: 'tense', positive: false, sort: 1 },
	{ nameDE: 'verzweifelt', nameEN: 'desperate', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'mutlos', nameEN: 'discouraged', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'niedergeschlagen', nameEN: 'dejected', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'deprimiert', nameEN: 'depressed', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'enttäuscht', nameEN: 'disappointed', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'hoffnungslos', nameEN: 'hopeless', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'traurig', nameEN: 'sad', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'schwermütig', nameEN: 'melancholic', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'bedrückt', nameEN: 'oppressed', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'gekränkt', nameEN: 'hurt', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'verletzt', nameEN: 'injured', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'elend', nameEN: 'miserable', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'unglücklich', nameEN: 'unhappy', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'kleinmütig', nameEN: 'despondent', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'beschämt', nameEN: 'ashamed', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'verlegen', nameEN: 'embarrassed', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'schuldig', nameEN: 'guilty', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'befangen', nameEN: 'self-conscious', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'reumütig', nameEN: 'remorseful', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'zerknirscht', nameEN: 'contrite', category: 'painful', positive: false, sort: 1 },
	{ nameDE: 'müde', nameEN: 'tired', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'kraftlos', nameEN: 'powerless', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'erschöpft', nameEN: 'exhausted', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'lethargisch', nameEN: 'lethargic', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'matt', nameEN: 'weary', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'kaputt', nameEN: 'broken', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'ausgelaugt', nameEN: 'drained', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'abgespannt', nameEN: 'worn out', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'lustlos', nameEN: 'listless', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'energielos', nameEN: 'energyless', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'apathisch', nameEN: 'apathetic', category: 'tired', positive: false, sort: 1 },
	{ nameDE: 'empört', nameEN: 'indignant', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'erbost', nameEN: 'irate', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'ärgerlich', nameEN: 'annoyed', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'verärgert', nameEN: 'irritated', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'feindselig', nameEN: 'hostile', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'wütend', nameEN: 'angry', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'zornig', nameEN: 'furious', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'verbittert', nameEN: 'embittered', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'neidisch', nameEN: 'envious', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'eifersüchtig', nameEN: 'jealous', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'genervt', nameEN: 'annoyed', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'irritiert', nameEN: 'irritated', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'zynisch', nameEN: 'cynical', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'gereizt', nameEN: 'irritable', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'grimmig', nameEN: 'grim', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'missmutig', nameEN: 'disgruntled', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'verdrossen', nameEN: 'annoyed', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'unwillig', nameEN: 'unwilling', category: 'angry', positive: false, sort: 1 },
	{ nameDE: 'gleichgültig', nameEN: 'indifferent', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'desinteressiert', nameEN: 'disinterested', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'distanziert', nameEN: 'distant', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'zurückgezogen', nameEN: 'withdrawn', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'abgelenkt', nameEN: 'distracted', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'gelangweilt', nameEN: 'bored', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'unbeteiligt', nameEN: 'uninvolved', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'teilnahmslos', nameEN: 'indifferent', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'einsam', nameEN: 'lonely', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'isoliert', nameEN: 'isolated', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'taub', nameEN: 'numb', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'abgestumpft', nameEN: 'desensitized', category: 'disconnected', positive: false, sort: 1 },
	{ nameDE: 'verwirrt', nameEN: 'confused', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'durcheinander', nameEN: 'confused', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'verlegen', nameEN: 'embarrassed', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'unangenehm berührt', nameEN: 'uncomfortable', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'unschlüssig', nameEN: 'undecided', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'zweifelnd', nameEN: 'doubtful', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'hin- und hergerissen', nameEN: 'torn', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'ambivalent', nameEN: 'ambivalent', category: 'confused', positive: false, sort: 1 },
	{ nameDE: 'erleichtert', nameEN: 'relieved', category: 'relieved', positive: true, sort: 1 },
	{ nameDE: 'befreit', nameEN: 'liberated', category: 'relieved', positive: true, sort: 1 },
	{ nameDE: 'entspannt', nameEN: 'relaxed', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'ausgeglichen', nameEN: 'balanced', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'gelassen', nameEN: 'calm', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'ruhig', nameEN: 'calm', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'zufrieden', nameEN: 'content', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'wohl', nameEN: 'well', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'behaglich', nameEN: 'comfortable', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'sicher', nameEN: 'secure', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'geborgen', nameEN: 'safe', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'vertrauensvoll', nameEN: 'trusting', category: 'calm', positive: true, sort: 1 },
	{ nameDE: 'hoffnungsvoll', nameEN: 'hopeful', category: 'hopeful', positive: true, sort: 1 },
	{ nameDE: 'zuversichtlich', nameEN: 'confident', category: 'hopeful', positive: true, sort: 1 },
	{ nameDE: 'optimistisch', nameEN: 'optimistic', category: 'hopeful', positive: true, sort: 1 },
	{ nameDE: 'ermutigt', nameEN: 'encouraged', category: 'hopeful', positive: true, sort: 1 },
	{ nameDE: 'inspiriert', nameEN: 'inspired', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'begeistert', nameEN: 'enthusiastic', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'fasziniert', nameEN: 'fascinated', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'motiviert', nameEN: 'motivated', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'interessiert', nameEN: 'interested', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'neugierig', nameEN: 'curious', category: 'inspired', positive: true, sort: 1 },
	{ nameDE: 'aufgeregt', nameEN: 'excited', category: 'excited', positive: true, sort: 1 },
	{ nameDE: 'gespannt', nameEN: 'eager', category: 'excited', positive: true, sort: 1 },
	{ nameDE: 'erwartungsvoll', nameEN: 'expectant', category: 'excited', positive: true, sort: 1 },
	{ nameDE: 'voller Vorfreude', nameEN: 'anticipatory', category: 'excited', positive: true, sort: 1 },
	{ nameDE: 'kribbelig', nameEN: 'tingly', category: 'excited', positive: true, sort: 1 },
	{ nameDE: 'dankbar', nameEN: 'grateful', category: 'grateful', positive: true, sort: 1 },
	{ nameDE: 'beschenkt', nameEN: 'gifted', category: 'grateful', positive: true, sort: 1 },
	{ nameDE: 'berührt', nameEN: 'touched', category: 'grateful', positive: true, sort: 1 },
	{ nameDE: 'gerührt', nameEN: 'moved', category: 'grateful', positive: true, sort: 1 },
	{ nameDE: 'bewegt', nameEN: 'moved', category: 'grateful', positive: true, sort: 1 },
	{ nameDE: 'energiegeladen', nameEN: 'energized', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'lebendig', nameEN: 'alive', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'erfrischt', nameEN: 'refreshed', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'belebt', nameEN: 'invigorated', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'aufgeweckt', nameEN: 'awake', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'wach', nameEN: 'alert', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'angeregt', nameEN: 'stimulated', category: 'energized', positive: true, sort: 1 },
	{ nameDE: 'glücklich', nameEN: 'happy', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'freudig', nameEN: 'joyful', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'froh', nameEN: 'glad', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'fröhlich', nameEN: 'cheerful', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'heiter', nameEN: 'serene', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'beschwingt', nameEN: 'buoyant', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'beglückt', nameEN: 'elated', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'selig', nameEN: 'blissful', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'vergnügt', nameEN: 'pleased', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'heiter', nameEN: 'bright', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'unbeschwert', nameEN: 'carefree', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'leicht', nameEN: 'light', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'überschwänglich', nameEN: 'exuberant', category: 'happy', positive: true, sort: 1 },
	{ nameDE: 'stolz', nameEN: 'proud', category: 'proud', positive: true, sort: 1 },
	{ nameDE: 'erfüllt', nameEN: 'fulfilled', category: 'proud', positive: true, sort: 1 },
	{ nameDE: 'verbunden', nameEN: 'connected', category: 'connected', positive: true, sort: 1 },
	{ nameDE: 'angekommen', nameEN: 'arrived', category: 'connected', positive: true, sort: 1 },
	{ nameDE: 'liebevoll', nameEN: 'loving', category: 'loving', positive: true, sort: 1 },
	{ nameDE: 'warmherzig', nameEN: 'warm-hearted', category: 'loving', positive: true, sort: 1 },
	{ nameDE: 'zärtlich', nameEN: 'tender', category: 'loving', positive: true, sort: 1 },
	{ nameDE: 'verliebt', nameEN: 'in love', category: 'loving', positive: true, sort: 1 },
	{ nameDE: 'hingebungsvoll', nameEN: 'devoted', category: 'loving', positive: true, sort: 1 },
	{ nameDE: 'friedlich', nameEN: 'peaceful', category: 'peaceful', positive: true, sort: 1 },
	{ nameDE: 'zufrieden', nameEN: 'satisfied', category: 'peaceful', positive: true, sort: 1 },
	{ nameDE: 'erfrischt', nameEN: 'refreshed', category: 'refreshed', positive: true, sort: 1 },
	{ nameDE: 'ausgeruht', nameEN: 'rested', category: 'refreshed', positive: true, sort: 1 },
	{ nameDE: 'erholt', nameEN: 'recovered', category: 'refreshed', positive: true, sort: 1 },
	{ nameDE: 'verspielt', nameEN: 'playful', category: 'playful', positive: true, sort: 1 },
	{ nameDE: 'ausgelassen', nameEN: 'exuberant', category: 'playful', positive: true, sort: 1 },
	{ nameDE: 'amüsiert', nameEN: 'amused', category: 'playful', positive: true, sort: 1 },
	{ nameDE: 'erheitert', nameEN: 'amused', category: 'playful', positive: true, sort: 1 },
];

async function populate() {
	console.log('Populating feelings table...');

	for (const feeling of feelings) {
		try {
			await db.insert(feelingsTable).values({
				id: crypto.randomUUID(),
				nameDE: feeling.nameDE,
				nameEN: feeling.nameEN,
				category: feeling.category,
				positive: feeling.positive,
				sort: feeling.sort
			});
		} catch (error) {
			console.error(`Failed to insert feeling ${feeling.nameDE}:`, error);
		}
	}

	console.log(`✅ Inserted ${feelings.length} feelings`);
	process.exit(0);
}

populate();
